USE [master]
GO

/****** Object:  Database [crud_delphi]    Script Date: 05/01/2015 12:10:27 ******/
CREATE DATABASE [crud_delphi] ON  PRIMARY 
( NAME = N'crud_delphi', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\crud_delphi.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'crud_delphi_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\crud_delphi_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [crud_delphi] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [crud_delphi].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [crud_delphi] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [crud_delphi] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [crud_delphi] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [crud_delphi] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [crud_delphi] SET ARITHABORT OFF 
GO

ALTER DATABASE [crud_delphi] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [crud_delphi] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [crud_delphi] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [crud_delphi] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [crud_delphi] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [crud_delphi] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [crud_delphi] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [crud_delphi] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [crud_delphi] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [crud_delphi] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [crud_delphi] SET  DISABLE_BROKER 
GO

ALTER DATABASE [crud_delphi] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [crud_delphi] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [crud_delphi] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [crud_delphi] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [crud_delphi] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [crud_delphi] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [crud_delphi] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [crud_delphi] SET  READ_WRITE 
GO

ALTER DATABASE [crud_delphi] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [crud_delphi] SET  MULTI_USER 
GO

ALTER DATABASE [crud_delphi] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [crud_delphi] SET DB_CHAINING OFF 
GO

